GET http://localhost:3000/error

###
GET http://localhost:3000/

###

POST http://localhost:3000/api
Content-Type: application/json

{
    "content" : "this is the first note"
}
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "WenMingSoh",
    "name": "Soh Wen Ming",
    "password": "Holoq123holoq123"

}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "WenMingSoh",
    "password": "Holoq123holoq123"
}