GET http://localhost:3000/error

###
GET http://localhost:3000/

###

POST http://localhost:3000/api
Content-Type: application/json

{
    "content" : "this is the first note"
}
###
POST http://localhost:3000/users
Content-Type: application/json

{
    "body": "body"
}
